import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import Accueil from '../components/Acceuil'
import Section from '../components/Section'
import Baniere from '../components/Baniere'
import Team from '../components/Team'

export default function Home() {
  return (
    // <div className={styles.container}>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <Nav />
        {/* <Accueil /> */}
        <Baniere />
        

          <Team />
      

      <Footer />


      
    </>
  )
}
